### ISSUE TITLE
Hamburger nav not working

### ISSUE THREAD

**Issue by cazinc** [ror-community/ror-site#30] opened 2020-03-17 20:31 UTC
Looks like when the hamburger nav appears at smaller screen sizes, the slide out menu drawer isn't working. @mariagould can you confirm this? Seems to be a problem on dev and live. Do you want us to try and fix or is this one for Martin?

**Comment by cazinc** [comment] 2020-03-17 20:34
Probably related to introduction of the search field in header, and possibly somewhat related to #20 as well.

**Comment by mariagould** [comment] 2020-03-25 22:01
@cazinc I can confirm the hamburger nav does not work at smaller screen sizes. Agree it is likely related to #20 and also to https://github.com/ror-community/ror-api/issues/19 (hamburger nav not working on mobile)

Would be great if you could try to fix! Thank you.

**Comment by cazinc** [comment] 2020-03-27 10:26
Cool @mariagould we'll get to work on this!

**Comment by cazinc** [comment] 2020-03-27 14:39
@mariagould sorted now on dev, can you have a look and confirm if OK? If so you can close this and the related issues #20 and #19 too I think. 

BTW it seems like the hamburger menu may have never worked on smaller screens. There was some weirdness that dates back to when the new theme was added to the site.

**Comment by mariagould** [comment] 2020-03-31 23:51
Hi @cazinc I can get this to work on dev on all pages except /search.

**Comment by bcgwebdesign** [comment] 2020-04-01 06:54
it also **looks** different on the search page - is this a result of it being shared css/js (or not shared) since the search page is actually separate from the regular site pages @cazinc

**Comment by cazinc** [comment] 2020-04-14 20:42
Hi @mariagould just a quick update to say we have been working on this - sorry for having gone quiet. Its turned out to be quite a big job just because anything related to the search functionality on the site is a completely different set of code. Whatever was done previously with regard to bringing in the site-wide menu to the search page doesn't seem to have been working, and had also been built in a completely different way. We're trying to get everything functional and standardise a bit at the same time. We've also been a bit broadsided by work on the main Crossref site for the last couple of weeks, which isn't helping. Anyway - will get back to this soonest! Please let me know if you have any questions or concerns.

**Comment by cazinc** [comment] 2020-04-14 21:21
Sorry @mariagould Bruce I stand corrected - this is pretty much fixed after all, can you review? A couple small styling issues that we had a very difficult time with, but otherwise should be working.

**Comment by mariagould** [comment] 2020-04-15 00:22
Thanks @cazinc @bcgwebdesign I *think* this is all good now. I am still having caching issues so hard to be 100% sure, but I tested on desktop and mobile and was able to get the hamburger nav on /search. I will close this out. Thank you for your help & hard work!

**Closed by mariagould** 2020-04-15 00:22 UTC
Labels: website
