### ISSUE TITLE
New site - final tweaks

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#70] opened 2022-09-30 22:02 UTC
Hi @cazinc I'm almost done setting up all of our content on the new site. Here are a few new/outstanding issues I've come across in doing so, and a couple of general questions about the new config. 

**Issues/changes**
1. The "Resources" button link in the main nav still needs to be merged in, I believe (per #48)
2. For some reason, it looks like the H4 style is coming out larger than H3 (for an example, see the team member bios under "About") - can H4 be smaller?
3. Callout box icons are really large relative to callout box text - can they be a bit smaller? (for an example, see callout on "About" page). Also, is it possible to have a box option with no icon at all? (apologies for not mentioning this earlier)
4. As discussed in #51, can we add a line of text under the search box on the homepage that says, in small italic type, "Or go to the main search page to browse and view all registry records" (with "search page" linked to https://ror.org/search) (see screenshot)

![Screen Shot 2022-09-30 at 2 53 45 PM](https://user-images.githubusercontent.com/45110557/193362547-7595fcae-4979-4bfc-be59-d1e8c9618500.png)

**Questions**
1. The two images in the call-to-action/learn-more section of the homepage (Join the community / Learn more about ROR) are looking a little blurry. Do they need to have a specific resolution/dimension in order to look clearer?
2. The thumbnail image for the latest blog post (lion-statue-sq) is not showing up on the homepage or on the blog. Is there something else I need to do to get this image file in the directory?
3. I was able to figure out how to change the tagline on the homepage but I'm not clear how/where the homepage banner image is and how to replace it. I thought I'd ask you about this first without fiddling too much and possibly breaking something. 
4. I tried to make a small adjustment in the footer social links (changing "Support site" to "Support" but it looks like this change was only made on the homepage footer. Can you tell me where else I need to make the change so that the other pages show the updates as well? 

Thank you! Getting close!

**Comment by cazinc** [comment] 2022-10-03 10:13
Hi @mariagould, cool, thanks for update on progress. Just going through various things this morning, updates and answers on the issues noted here below:

*Issues/changes*

1. Yes you were right, `dev` branch was slightly behind `summer-2022-updates`. All updated now, and the new nav is showing. 
2. Fixed now, down to a small typo. We've also made H4s italic as the corrected size difference between these and H3s wasn't super evident. Let me know what you think. 
3. Several changes made to callout blocks: 
  - We've reduced the size of the icons by 25% on callout boxes.
  - Icon and text are now vertically centred, as we felt it works a bit better on the callout boxes with less text. 
  - There is a new "no-icon" option for you, info on how it works on https://dev.ror.org/test/ in the Callouts section. It felt more "natural" to leave the default as an info icon and make it necessary to explicitly state "no-icon" if you don't want one, but let me know if you differ. 
4. New text added. This made the search bar feel a bit "long" again so we've tweaked padding a tiny bit to compensate. 

*Questions*

1. I think the blurriness on these particular images is down to the originals. For example http://dev.ror.org/img/ror-ing-in-lisbon.jpg looks blurry to me even when it's much larger. On http://dev.ror.org/img/pride-leonard-von-bibra.jpg the lions in the background are blurry just because of the depth of field of the photo. Does this answer the question OK? In answer the larger question though, the ensure clarity the images only really have to be larger than the rendered version. By that I mean, if you uploaded a small image at say 200px x 100px, and on homepage these are blown up to 400px x 200px, you would get a bit of pixelation. But if you uploaded a larger image of say 600px x 400px, it will be resized **downwards** ok and stay sharp. 
2. Looks like there is something up with the image file itself, as it shows as Zero KB. Try dropping in new version and it should fix this (the frontmatter etc. all seem OK).
3. The banner image on home is configured in the site config.toml file. These exist for each site in the root, so you'll see for example localhost.toml, staging.toml, etc. Open up the localhost one to start and look for the `[params]` section, and then `image`. Screenshot attached for ref. It would be best to try and match the exact dimensions of the current image if poss, unless you are wanting to make it a bit shorter for example. Between having 4 .toml files and also the various Git branches this can get a bit confusing, so just shout if questions. 
4. Changes to footer links should be global, and looking at it now all pages seem the same. Just to double-check, if you changed text for the Support link, you would do it in `../data/socials/6.yaml`. Let me know how you get on. 

Hope that all helps!

**Comment by cazinc** [comment] 2022-10-03 12:51
BTW @mariagould all the above now merged into `dev` branch. 

We've made a couple small styling changes and fixes, so you may want to refresh the page a couple times when viewing https://dev.ror.org just to make sure these are in play rather than an older cached version.

**Comment by amandafrench** [comment] 2022-10-03 16:19
Small bug with the Support button in the main nav: as expected, when I click on it from any page, say /about, it launches a new tab with ror.readme.com. But when I return to the tab with the /about page loaded, the Support button is gone. Or at least it's white text in a white button. Clicking or hovering on the /about page brings it back, in Firefox at least. It behaves a little differently but still weirdly in Chrome.

**Comment by mariagould** [comment] 2022-10-04 04:26
Thanks for following up @cazinc - I'm reviewing your comments and will get back to you in the next day or so! Thanks!

**Comment by cazinc** [comment] 2022-10-05 15:17
Hi @amandafrench we've just pushed a small fix to colouring that should help. After that it's currently 'expected behaviour' but we can look at other ways to address. Basically:

1. When you click the Support button at top right, it opens a new tab. At this point the button has focus;
2. The button retains focus in the previous tab while you are taken to the new tab;
2. When you come back from the new tab you have to click in the old tab somewhere to break the focus and return the button to it's normal state (this is where the colour fix will help, as it's now 'stuck' as green text on grey rather than white on grey). 

If fixing the colour is sufficient then I think it's sorted. If you feel the way the button appears "stuck in hover mode" is a bit wonky, we could restyle things to remove or minimise the effect, though ultimately that would limit or remove the on hover feedback. Probably could fix with some javascript too. 

Let me know what you think.

**Comment by amandafrench** [comment] 2022-10-06 18:55
Perfect, thanks. No more white text on white background in either Firefox or Chrome.

**Comment by mariagould** [comment] 2022-10-07 14:09
Hi @cazinc I'm trying to review the changes in items 2 and 3 but I can't see most of the content on the pages. There seems to be some issue with scrolling impacting the display of the main page body. Screenshots below. I've reproduced this in Chrome, Firefox, and Safari. 

For item 1 (main nav), everything looks good to go.

For item 4 (search link on homepage), can we make a couple of tiny tweaks:
- Left-align the new text instead of centering
- Change text to "Or go to the main search page to browse all ROR records" (with "search page" still linked to the ror.org/search as it is currently)

Thank you!


> BTW @mariagould all the above now merged into `dev` branch.
> 
> We've made a couple small styling changes and fixes, so you may want to refresh the page a couple times when viewing https://dev.ror.org just to make sure these are in play rather than an older cached version.

**Comment by cazinc** [comment] 2022-10-10 08:46
Hi @mariagould

That issue preventing you from reviewing is fixed now, sorry about that. 

With regard to left aligning the text, I wasn't sure exactly which element you wanted things aligned to (left of the content below, left in line with the "Search" text above, etc.) so we've taken a stab at something, let me know what you think, or if you had something else in mind. In order to do this we've also aligned the Search bar itself, which was previously centred.

**Comment by cazinc** [comment] 2022-10-11 10:36
Hi @mariagould we've updated per your mockup now, thanks for clarifying.

**Comment by mariagould** [comment] 2022-10-11 23:05
Thanks @cazinc looks much better now!

In terms of remaining items, I think we're all set with the new H4 and callout box updates. 

Regarding the homepage image, I tried to replace one where you suggested but I seem to have broken it entirely. I edited it in dev.toml because that's where I was making other updates. I first updated the file in `[params]` and nothing changed. Then I noticed the file name also appeared in `[params.landingbanner]` so I updated it there as well. And then when I deployed the image disappeared completely. Can you provide a little more guidance as to how I might go about updating the image? Thanks.

I'm asking the team to give another glance over the site overall to see if there are any other issues I might not have spotted, and then once that's done, I think we'll be clear to proceed to launch!

**Comment by cazinc** [comment] 2022-10-12 14:02
Hi @mariagould 

Good spot - the first `image` param was the wrong one, it is in fact the one under `[params.landingbanner]`. (The first one is a remnant of config for a carousel in the banner area, we've removed it now for clarity.)

Your change was fine except that you had the path slightly wrong. ROR_Lions_Banner.jpg file is in the `../img` folder, not `../img/banners`. I've updated the toml file accordingly, but you could also move the file to the `/banners` directory and then change the path back if you want to keep it neat. 

FYI if you are using `sh preview-local.command` I have synced the localhost.toml file with dev.toml now. live.toml will also need synced when all this goes live.

**Comment by mariagould** [comment] 2022-10-12 23:59
Thanks @cazinc ! I am happy to keep the hero image in the main `/img` folder for now unless you think it's better to move it back!

**Comment by cazinc** [comment] 2022-10-13 07:56
Happy to leave where it is!

**Comment by mariagould** [comment] 2022-10-13 22:16
Hi @cazinc after team review, here are a couple of small final fixes:

**1. Adjust link color in callout boxes**: can we use the default teal link color in the gray callout, and white in all of the other box styles? I'm concerned about links not being obvious, especially in the gray callout (example at /about/faqs). 

**2. Add a bit more padding at the bottom of every page before the footer** The padding is slight so it seems almost like page content is being cutoff (even though it's not). 

<img width="1159" alt="Screen Shot 2022-10-13 at 3 08 06 PM" src="https://user-images.githubusercontent.com/45110557/195719889-eff82185-1b25-4a3c-a5bf-a6411e764277.png">

**3. Possible bug with `centered` shortcode?** I tried to add a centered button on /community#supporters but the centered style does not seem to be working. To rule out a typo issue, I tried both `centered` and `center` but in both cases the button remains left-aligned. Am I doing something wrong, or is there a bug with the shortcode?

**4. Display of featured images on homepage.** The homepage image next to "Use the registry" has a white background so I tried to add a border to it (in the image editor) to make it stand out from the page background. However, the top and bottom borders do not display despite my attempts at making the borders thicker and re-sizing the image to be smaller. Is there something else I can do to make the borders display (or some other way to make an image with white background standout from the page background?)

**5. Browser issues?** I'm not sure if this is due to cacheing or something else but depending on which browser I use to preview changes on dev, I'm not seeing certain elements. Featured homepage images are missing in Safari, and in Firefox the ROR logo is missing. Everything looks fine in Chrome. 

That's it. Thank you!

**Comment by cazinc** [comment] 2022-10-14 08:58
Hi @mariagould, 

Responses on the latest issues below:

1. Done. You can see how the text and link colours play out in all the possible combos on https://dev.ror.org/test/.
2. Done. 
3. What's actually needed here is wrapping the element you want to centre (the whole button for example) in `{{% centered % }} ... {{% /centered %}}`. The `style="center"` on the button itself doesn't work, and apologies for confusion. I think that was a leftover of wherever the button came from originally. I've updated your example on the Community page so you can see it in action. 
4. The way these images are resized to fit in the page means that they will sometimes be cropped at top and bottom, and it's not actually possible to get the dimensions "just right" to avoid this (and would result in the images being different sizes sometimes in any case). We could rejig things to give you the ability to specify a border maybe? 
5. I can see the issue in Firefox with the logo, not sure what's up but we'll get it fixed. I don't think I can see the issue with Safari though, see attached. Maybe try it in a Private Window to see if that makes any diff? 
<img width="1491" alt="Screenshot 2022-10-14 at 09 50 46" src="https://user-images.githubusercontent.com/3863704/195806659-cb08b226-9899-413b-99fc-2b8758ab0894.png">

Will come back on that Firefox issue!

**Comment by cazinc** [comment] 2022-10-14 12:02
That's the Firefox issue resolved now too @mariagould. 

We also noted that the ROR log was replaced with a textual "ROR" on mobiles, so given the logo is small enough anyway we've removed that and the logo now shows at all screen sizes. Hope that's OK.

**Comment by mariagould** [comment] 2022-10-14 14:47
Thanks for the fixes @cazinc! 

Re: homepage photo, I think let's just leave it alone for now and I'll see what I can do on my end. 

Re: Safari, the images are showing up now, so I think we're all good. 

One new question: is there a rule for styling links as bold vs. not-bold? It seems like the default is set to bold, but I'm seeing some cases where they are not bold in bulleted lists (e.g., see /community).

**Comment by cazinc** [comment] 2022-10-14 14:58
That issue with links on the Community page should be fixed now @mariagould - give it a few minutes to build on dev.ror.org, or if you pull down latest you'll get it locally. 

The style that makes links bold was a very specifically targeted at only links within paragraphs. I've expanded it to cover lists as well. If you spot anything else like that just let us know.

**Comment by mariagould** [comment] 2022-10-14 19:19
Thanks! Looks fine now!

Now that it seems as though we're in a good place to proceed, what do we need to do to move forward with deployment on stage/production?

**Comment by cazinc** [comment] 2022-10-17 08:33
Great - got there in the end!

I just tried a test merge of dev into staging and there are really just 2 conflicts, in this case content files that differ between the two branches (both blog posts). The fix could be as easy as accepting the newer ones. 

There are a further 2 files that exist in staging but not in dev.

Given the issues are all in content, it might be easier for you to try this merge at your end, but happy to do it in a call or even just to list the issues for you here if you'd rather do it that way. 

Once these small conflicts are resolved you can commit the merge to staging, and then I would expect the merge to live to be OK.

**Comment by lizkrznarich** [comment] 2022-10-17 15:34
@mariagould @cazinc Before deploying to production, we'll need to handle the menu and footer in ror-app.

**Comment by cazinc** [comment] 2022-10-17 15:44
Thanks for the reminder @lizkrznarich. 

Do you know if amends to the dev branch of `ror-app` are deployed to https://dev.ror.org/search when committed?

**Comment by lizkrznarich** [comment] 2022-10-17 15:54
@cazinc yup, works similar to ror-site, except that deployment to prod requires a release https://github.com/ror-community/ror-app#deployment . would appreciate pull requests from a feature branch to dev rather than commits directly to dev, as i'm actively doing some work on ror-app (small changes to the data being displayed, not the layout or style). I will also open PRs against dev, so we don't trip over each other.

**Comment by mariagould** [comment] 2022-10-17 20:52
Hi @cazinc - just building on the guidance from Liz re: deployment, I wanted to clarify a couple of things and summarize the plan for ror-app to make sure we're all aligned. 

- `ror-app` needs to reflect the updated main nav menu changes, with one key exception: we need to retain the search box in the `ror-app` header so that when users are viewing records at `/search`, they are able to perform a search operation. 

- the footer in `ror-app` should be the same as for `ror-site`

- follow @lizkrznarich instructions for getting the `ror-app` changes committed to dev, and then Liz and I can handle merging to staging. 

@lizkrznarich I think I've captured everything but please add anything else as you see fit!

**Comment by cazinc** [comment] 2022-10-18 14:45
Hi @mariagould @lizkrznarich we've just submitted a pull request for the nav and footer updates. 

Maria we haven't brought over the new social block just because doing so would mean it's hard-coded, and not linked to the new flexible model on the main site. Do you want it brought over anyway?

**Comment by mariagould** [comment] 2022-10-18 15:28
Hi @cazinc I think it would be preferable to have the new social block in the `ror-app` footer as well. @lizkrznarich do you have any concerns about doing this?

**Comment by lizkrznarich** [comment] 2022-10-18 15:30
Nope, no concerns from me, but per my note on https://github.com/ror-community/ror-app/pull/99#issuecomment-1282523392, please push the changes up to the remote branch (they don't appear to be there yet).

**Comment by cazinc** [comment] 2022-10-18 16:31
Sorry @lizkrznarich, forgot to push them!

**Comment by cazinc** [comment] 2022-10-18 16:31
@mariagould we'll get the socials block added in shortly.

**Comment by lizkrznarich** [comment] 2022-10-18 16:43
@cazinc Looks good! I'll just wait for the social icons before I merge and deploy to dev.

**Comment by cazinc** [comment] 2022-10-18 18:03
Hi @lizkrznarich that's the socials block pushed now.

**Comment by lizkrznarich** [comment] 2022-10-21 17:58
@cazinc Working on ror-app, I've noticed that some Bootstrap form controls are overridden in the ror-site theme, ex checkbox inputs are hidden https://github.com/ror-community/ror-site/blob/dev/themes/hugo-ror/assets/sass/main.css#L13038 . This is making it a bit miserable to work with standard Bootstrap form controls, as I have to reset the CSS back to the Bootstrap defaults. Are these form control styles actually used in ror-site? If not, can these overrides be removed?

**Comment by cazinc** [comment] 2022-10-22 09:51
@lizkrznarich I think all those overrides are from before our time, part of the original Theme that the ROR site is based on, which had a complicated set of options for colours etc. I've moved a load of them out into SASS partials just in case, but they aren't being loaded. We only had 2 input fields in the ror-site so no big deal for us. 

I can see some knock on effects on the ror-app site, e.g. the search bar in header - do you want to fix that as part of what you are doing?

**Comment by lizkrznarich** [comment] 2022-10-22 14:04
@cazinc Sorry about that and thanks! I should have looked more closely - I had searched master in Github, and didn't find those styles, but I see they are in the ror-css file. Yes, I'll double-check that all those bootstrap overrides aren't being used and remove them. @mariagould Since it doesn't really affect ror-site, we can continue on with releasing it as planned.

**Comment by cazinc** [comment] 2022-10-24 10:31
No problem at all. I was just reviewing the site and noticed that we managed to unset the new Atkinson font as part of pulling out the form styling, so we've fixed that now. 

Just a reminder (because it's the sort of thing I would totally forget!) to repoint `ror-app` at the live CSS at a final stage of release. See line 19 of `../app/index.html`. We pointed it at `dev.ror.org/css/` just so that the new styling amends would be visible on dev.ror.org.

**Comment by amandafrench** [comment] 2022-11-07 19:58
@cazinc Hi Zach, speaking of CSS -- if we want to make changes to the CSS in the future, say add a new style or modify an existing one, which CSS files should we edit?

**Comment by amandafrench** [comment] 2022-11-08 13:41
@cazinc Yep, I'm familiar with SASS! That's what I figured. Thanks.

**Comment by cazinc** [comment] 2022-11-08 13:45
Ah great, that makes it easy!

**Comment by cazinc** [comment] 2022-11-09 17:00
Hi @amandafrench @mariagould a couple things re: fonts:

Geoff has just pointed out that the main Crossref site is using Google fonts, and this is looking like a no-no now. See https://www.google.com/search?q=google+fonts+eu&oq=google+fonts+eu&aqs=chrome..69i57j0i19i512l6j69i60.6977j0j7&sourceid=chrome&ie=UTF-8 for more info. 

It should be relatively easy to shift to using Atkinson Hyperlegible locally instead of via Google, would you like us to do this? 

**On a related note, the live ROR APP is still using the CSS from the dev.ror.org site.** This means that if we were to make any changes in the dev branch of ROR, for example related to changing fonts, it would also effect the live ROR APP. Shall we fix that in the master branch of ROR APP? This is what my reminder was referring to back on 24 October.

**Comment by lizkrznarich** [comment] 2022-11-09 17:13
@cazinc We're not responsible for decisions on the main Crossref site, so I think @ynnig (Ginny Hendricks) would be the contact for the fonts question there. RE: the ror-app css URL. I have that change on a branch, however, there are some things currently on dev in ror-app that I need to feature flag before I can merge into staging and prod. Will take care of it.

**Comment by ynnig** [comment] 2022-11-09 17:23
I think what Zach means is that if the ROR site is pulling from Google (any font) then that's not great for GDPR as google asks for IP details from the user before loading the page. (We're fixing this on the cr site so should probably be done on the ROR site too).

**Comment by lizkrznarich** [comment] 2022-11-09 17:44
Ack, sorry @ynnig @cazinc  - I totally misread that! Might as well move the fonts local. The German court Google Fonts ruling is a bit nonsensical, but storing fonts locally is generally good for other reasons as well.

**Comment by mariagould** [comment] 2022-11-09 19:29
Yes, agreed. Thanks for flagging this!

**Comment by cazinc** [comment] 2022-11-10 08:36
Hi @lizkrznarich sorry, I should have said we were already working on changing out the fonts on the Crossref site per Ginny, sorry. Thanks for update on dev ROR css too. 

@mariagould we'll get to work on moving the font local soonest.

**Comment by cazinc** [comment] 2022-11-30 11:40
Hi @lizkrznarich @mariagould I failed to post an update here, but we made changes to move the fonts local back on the 11th November - there was a [pull request](https://github.com/ror-community/ror-site/pull/77) submitted for this.

**Closed** 2023-01-25 01:47 UTC
